import Head from 'next/head';
import dynamic from "next/dynamic";

const Main = dynamic(() => import('../pages/main'), { ssr: false });

export default function App() {
  return (
    <div>
      <Head>
        <title>Peatland vs Palm Oil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main />
    </div>
  )
}